#访问端口设为 80
server.port: 80
#tomcat-url encoding : utf-8
server:
  tomcat:
    uri-encoding: UTF-8


#=====================================================================
#数据源配置 采用HikariCP

#jdbc config
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.101.154.133:3306/hannah?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&serverTimezone=GMT
    username: root
    password: "034816"
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      connection-timeout: 30000
      minimum-idle: 15
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 60000
      pool-name: DatabookHikariCP
      max-lifetime: 28740000
      connection-test-query: select 1


#=====================================================================

#=====================================================================
#mybatis 配置
#
mybatis:
  type-aliases-package: per.lijun.hannah.entity
  mapper-locations: classpath:per.lijun.hannah.mapper/*.xml
mapper:
  mappers: per.lijun.hannah.base.MyMapper
  not-empty: false
  identity: MYSQL
pagehelper:
  helper-dialect: mysql
  support-methods-arguments: true
  params: count=countSql

#========================================================================


#========================================================================
#dfs 配置
#
fdfs:
  so-timeout: 1501
  connect-timeout: 601
  thumb-image:             #缩略图生成参数
    width: 100
    height: 100
  tracker-list[0]: 47.101.154.133:22122

#========================================================================

logging:
  level:
   com:
    withmes: trace
  path: logs/hannah_dev.log